import streamlit as st
import datetime
import requests

#from exception.exceptions import TradingBotException
import sys

import os

# Backend Point: Use environment variable for deployment, fallback to localhost for local runs
BASE_URL = os.getenv("API_URL", "http://localhost:8000")

st.set_page_config(
    page_title="🌏 Travel Planner Agentic Application",
    page_icon="🌏",
    layout = "centered",
    initial_sidebar_state="expanded",

)

st.title("🌏 Travel Planner Agentic Application")

#initialize chat history
if "messages" not in st.session_state:
    st.session_state.messages = []

st.header("How can I assist you in planning your trip today? Let me know where do you want to visit.")

#chat input box at bottom
with st.form(key="query_form", clear_on_submit=True):
    user_input=st.text_input("User Input", placeholder="E.g. Plan a trip to Goa for 5 days")

    submit_button=st.form_submit_button("Send")

if submit_button and user_input.strip():
    try:

        #showing user message
        #then also show THINKING spinner while backend processes
        with st.spinner("Thinking..."):
            payload = {"question": user_input}
            response = requests.post(f"{BASE_URL}/query", json=payload)

        if response.status_code == 200:
            answer = response.json().get("answer", "Sorry, I couldn't get an answer.")
            markdown_content=f"""#🌏AI Travel Plan

            {answer}

            """
            #This travel plan is generated by AI. Please verify all information, especially prices.

            st.markdown(markdown_content)
        else:
            st.error("Error : Failed to get response from the travel agent." + response.text)

    except Exception as e:
        raise Exception(f"The response failed due to {e}")
    


            


            
        


